# Number of parallel crawl jobs
num_processes = 2

# Logging level (DEBUG, INFO, WARN, or ERROR)
log_level = "DEBUG"

[twitter_api]
consumer_key = "YOUR_CONSUMER_KEY_HERE"
consumer_key_secret = "YOUR_CONSUMER_KEY_SECRET_HERE"
access_token = "YOUR_ACCESS_TOKEN_HERE"
access_token_secret = "YOUR_ACCESS_TOKEN_SECRET_HERE"
