[build-system]
requires = ["setuptools>=40.8.0", "wheel", "setuptools_scm~=3.3"]
build-backend = "setuptools.build_meta"

[tool.isort]
line_length = 88
multi_line_output = 3
force_grid_wrap = 0
include_trailing_comma = true
use_parentheses = true

[tool.black]
target-version = ['py36']
quiet = true

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py36, py37, py38, check
isolated_builds = true
install_command = python -m pip install {opts} {packages} && pipenv install --dev --ignore-pipfile

[testenv]
commands = make test
whitelist_externals = make
deps = pipenv
setenv = PIPENV_VERBOSITY=-1
description = Run the unit tests under {basepython}.

[testenv:check]
commands = make check
description = Run linters, check formatting and static typing.
"""
